### ISSUE TITLE
Milestone v1

### ISSUE THREAD

**Issue by pandeyanujk** [memser-spaceport/pln-events#8]
- Event Type - Conference, virtual, social
- Attributes - event short description, logo
- Flag as a featured event
- event interaction - like, going, registering, etc. 
- Map view
- Filters
- Ability to paginate
- Event logo

**Comment by abarna-visvanathan** [comment]
#24

**Comment by abarna-visvanathan** [comment]
- [ ] https://github.com/memser-spaceport/pln-events/issues/1
- [ ] https://github.com/memser-spaceport/pln-events/issues/18
- [ ] https://github.com/memser-spaceport/pln-events/issues/17
- [ ] https://github.com/memser-spaceport/pln-events/issues/2
- [ ] https://github.com/memser-spaceport/pln-events/issues/3
- [ ] https://github.com/memser-spaceport/pln-events/issues/6
- [ ] https://github.com/memser-spaceport/pln-events/issues/4
- [ ] https://github.com/memser-spaceport/pln-events/issues/7
- [ ] https://github.com/memser-spaceport/pln-events/issues/11
- [ ] https://github.com/memser-spaceport/pln-events/issues/24
- [ ] https://github.com/memser-spaceport/pln-events/issues/22
- [ ] https://github.com/memser-spaceport/pln-events/issues/21
- [ ] https://github.com/memser-spaceport/pln-events/issues/30
- [ ] https://github.com/memser-spaceport/pln-events/issues/31
- [ ] https://github.com/memser-spaceport/pln-events/issues/32
- [ ] https://github.com/memser-spaceport/pln-events/issues/33
- [ ] https://github.com/memser-spaceport/pln-events/issues/43
- [ ] https://github.com/memser-spaceport/pln-events/issues/44
- [ ] https://github.com/memser-spaceport/pln-events/issues/45
- [ ] https://github.com/memser-spaceport/pln-events/issues/46
- [ ] https://github.com/memser-spaceport/pln-events/issues/51
- [ ] https://github.com/memser-spaceport/pln-events/issues/52
- [ ] https://github.com/memser-spaceport/pln-events/issues/91
- [ ] https://github.com/memser-spaceport/pln-events/issues/101
- [ ] https://github.com/memser-spaceport/pln-events/issues/128
